import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Router, { useRouter } from "next/router";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [searchQuery, setSearchQuery] = useState("");
    const router = useRouter();

    const handleChange = e => {
        setSearchQuery(e.target.value);
    };
    const handleSubmit = e => {
        e.preventDefault();
        router.push(`search/${searchQuery}`);
        setSearchQuery("");
    };

    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        <a href="https://nytimes.com">NYTimes</a> News
                    </h1>

                    <p className={styles.description}>
                        Type in to search for news:
                    </p>
                    <div className={styles.newsSearch}>
                        <form onSubmit={handleSubmit}>
                            <input
                                type="text"
                                name="query"
                                onChange={handleChange}
                                placeholder="Search for news"
                            />
                        </form>
                        <small>
                            E.g. Arts & Leisure Arts Automobiles Blogs Books
                            Booming Business Day Business Cars Circuits
                            Classifieds Connecticut Crosswords & Games Culture
                            DealBook Dining Editorial Education Energy
                            Entrepreneurs Environment Escapes Fashion & Style
                            Fashion Favorites Financial Flight Food Foreign
                            Generations Giving Global Home Health & Fitness
                            Health Home & Garden Home Jobs Key Letters Long
                            Island Magazine Market Place Media
                        </small>
                    </div>

                    <div className={styles.grid}>
                        <a href="/news/top-stories" className={styles.card}>
                            <h2>Top Stories &rarr;</h2>
                            <p>
                                Find in-depth information about Next.js features
                                and API.
                            </p>
                        </a>

                        <a href="/news/popular" className={styles.card}>
                            <h2>Popular &rarr;</h2>
                            <p>
                                Learn about Next.js in an interactive course
                                with quizzes!
                            </p>
                        </a>

                        <a href="/section" className={styles.card}>
                            <h2>Sections &rarr;</h2>
                            <p>
                                Learn about Next.js in an interactive course
                                with quizzes!
                            </p>
                        </a>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by{" "}
                        <span className={styles.logo}>
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                width={72}
                                height={16}
                            />
                        </span>
                    </a>
                </footer>
            </div>
        </Layout>
    );
}
